// Layout Component
import Layout from "@/components/layout/Layout";

// Sections - Functional Components
import Category from "@/components/sections/Category";
import Shop from "@/components/sections/Shop";

// Sections - Product Displays
import DealProduct1 from "@/components/sections/DealProduct1";
import HomeSupply from "@/components/sections/HomeSupply";
import Product1 from "@/components/sections/Product1";

// Sections - Media and Sliders
import Slider1 from "@/components/sections/Slider1";
export const metadata = {
  title: 'LaFoods Service',
  description: 'Generated by create next app',
}
export default function Home() {
    return (
        <>
            <Layout headerStyle={1} footerStyle={1}>
                <Slider1 />
                <HomeSupply />
                <Category />
                <Product1 />
                <DealProduct1 />
                {/* <Shop /> */}
            </Layout>
        </>
    )
}